version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      radix-ui:
        patterns:
          - "@radix-ui/*"
      dev-deps:
        dependency-type: development
      production-minor-patch:
        dependency-type: production
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
